/* Japanese vocabulary for Kawaishi — ported from the Judo Names Trainer.
   names: technique names (r=romaji, j=kanji, h=Hebrew, m=meaning, b=root breakdown, c=category).
   roots: building blocks (r=romaji, k=kanji, en=English, he=Hebrew, group=action|body|mod|special).
   Generated by build_vocab.js. */
window.KAWAISHI_VOCAB = {
  version: 1,
  names: [
  {
    "r": "Katate-Jime",
    "j": "片手絞",
    "h": "חניקת דש ביד אחת",
    "m": "One-hand strangle",
    "b": "Kata (single) + te (hand) + jime (choke)",
    "c": "Chokes",
    "y": "cHeIs-fSqwE"
  },
  {
    "r": "Gyaku-Juji-Jime",
    "j": "逆十字絞",
    "h": "חניקת צלב הפוכה",
    "m": "Reverse cross strangle (fingers in)",
    "b": "Gyaku (reverse) + juji (cross) + jime (choke)",
    "c": "Chokes",
    "y": "t3tQriIPdlI"
  },
  {
    "r": "Nami-Juji-Jime",
    "j": "並十字絞",
    "h": "חניקה בהצלבה",
    "m": "Normal cross strangle",
    "b": "Nami (normal) + juji (cross) + jime (choke)",
    "c": "Chokes",
    "y": "k2cHry9HByQ"
  },
  {
    "r": "Kata-Juji-Jime",
    "j": "片十字絞",
    "h": "חניקת חצי-צלב",
    "m": "Half cross strangle",
    "b": "Kata (half) + juji (cross) + jime (choke)",
    "c": "Chokes",
    "y": "3VZVUAmiMD8"
  },
  {
    "r": "Hadaka-Jime",
    "j": "裸絞",
    "h": "חניקה ידיים חשופות",
    "m": "Naked strangle",
    "b": "Hadaka (naked) + jime (choke)",
    "c": "Chokes",
    "y": "9f0n8jez7iA"
  },
  {
    "r": "Mae-Hadaka-Jime",
    "j": "前裸絞",
    "h": "חניקת גיליוטינה",
    "m": "Front guillotine",
    "b": "Mae (front) + hadaka (naked) + jime (choke)",
    "c": "Chokes"
  },
  {
    "r": "Okuri-Eri-Jime",
    "j": "送襟絞",
    "h": "חניקת דשים גולשת",
    "m": "Sliding lapel strangle",
    "b": "Okuri (sliding) + eri (collar) + jime (choke)",
    "c": "Chokes",
    "y": "EiqyoVcIAi8"
  },
  {
    "r": "Kataha-Jime",
    "j": "片羽絞",
    "h": "חניקת כנף אחת",
    "m": "Single wing strangle",
    "b": "Kata (single) + ha (wing) + jime (choke)",
    "c": "Chokes",
    "y": "yaTGgRjnwB8"
  },
  {
    "r": "Ryote-Jime",
    "j": "両手絞",
    "h": "חניקה בשתי ידיים",
    "m": "Two-hand strangle",
    "b": "Ryo (both) + te (hand) + jime (choke)",
    "c": "Chokes",
    "y": "-RHC4V7TQiY"
  },
  {
    "r": "Kesa-Gatame",
    "j": "袈裟固",
    "h": "ריתוק צעיף",
    "m": "Scarf hold",
    "b": "Kesa (scarf) + gatame (hold)",
    "c": "Pins",
    "y": "NDaQuJOFBYk"
  },
  {
    "r": "Kata-Gatame",
    "j": "肩固",
    "h": "ריתוק כתף",
    "m": "Shoulder hold",
    "b": "Kata (shoulder) + gatame (hold)",
    "c": "Pins",
    "y": "zQR3IOXxO_Q"
  },
  {
    "r": "Kami-Shiho-Gatame",
    "j": "上四方固",
    "h": "ריתוק צפון-דרום",
    "m": "Upper four quarter hold down",
    "b": "Kami (upper) + shiho (four-corner) + gatame (hold)",
    "c": "Pins",
    "y": "HFuMjOv0WN8",
    "n": "Shiho = ‘four directions’ — a four-corner hold controlling all of uke’s quarters."
  },
  {
    "r": "Yoko-Shiho-Gatame",
    "j": "横四方固",
    "h": "ריתוק צד (ארבע נקודות)",
    "m": "Side four quarter hold",
    "b": "Yoko (side) + shiho (four-corner) + gatame (hold)",
    "c": "Pins",
    "y": "TT7XJVSEQxA",
    "n": "Shiho = ‘four directions’ — a four-corner hold, here controlling uke’s quarters from the side."
  },
  {
    "r": "Kuzure-Kami-Shiho-Gatame",
    "j": "崩上四方固",
    "h": "ריתוק צפון-דרום שבור",
    "m": "Broken upper four quarter hold down",
    "b": "Kuzure (broken) + kami (upper) + shiho (four-corner) + gatame (hold)",
    "c": "Pins",
    "y": "YUrogQWdwiY",
    "n": "Kuzure = ‘broken’ = a modified variant: trap an arm and angle off the straight north–south line (more to the side). Shiho = four-corner control."
  },
  {
    "r": "Ude-Garami",
    "j": "腕緘",
    "h": "נעילת זרוע מקופלת (קימורה)",
    "m": "Arm entanglement (figure-four armlock)",
    "b": "Ude (arm) + garami (entanglement)",
    "c": "Arm locks",
    "y": "AIlTvZb4RlE"
  },
  {
    "r": "Ude-Gatame",
    "j": "腕固",
    "h": "נעילת זרוע ישרה",
    "m": "Straight armlock",
    "b": "Ude (arm) + gatame (lock)",
    "c": "Arm locks",
    "y": "SBf0aTma1VI"
  },
  {
    "r": "Ude-Hishigi-Hiza-Gatame",
    "j": "腕挫膝固",
    "h": "נעילת מרפק על הברך",
    "m": "Knee armbar",
    "b": "Ude (arm) + hishigi (crush) + hiza (knee) + gatame (lock)",
    "c": "Arm locks",
    "y": "H2HtAJdiJcE"
  },
  {
    "r": "Ude-Hishigi-Juji-Gatame",
    "j": "腕挫十字固",
    "h": "נעילת זרוע צולבת",
    "m": "Cross armbar (lever)",
    "b": "Ude (arm) + hishigi (crush) + juji (cross) + gatame (lock)",
    "c": "Arm locks",
    "y": "OWgSOlCuMXw"
  },
  {
    "r": "Ude-Hishigi-Ashi-Gatame",
    "j": "腕挫脚固",
    "h": "נעילת מרפק על הרגל",
    "m": "Armbar over the leg",
    "b": "Ude (arm) + hishigi (crush) + ashi (leg) + gatame (lock)",
    "c": "Arm locks",
    "y": "ClY7g_pX-4s"
  },
  {
    "r": "Sankaku-Jime",
    "j": "三角絞",
    "h": "חניקת משולש עם שבירת יד",
    "m": "Triangular strangle (Triangle choke)",
    "b": "Sankaku (triangle) + jime (choke)",
    "c": "Arm locks",
    "y": "lq1CUBRAm7s"
  },
  {
    "r": "Hammerlock",
    "j": "—",
    "h": "נעילת יד מאחורי הגב",
    "m": "Arm behind the back",
    "b": "English term — arm bent behind the back",
    "c": "Arm locks",
    "n": "Not a Kodokan Japanese name — an English term for bending uke’s arm up behind the back (police-style restraint). No standard kanji."
  },
  {
    "r": "Ashi-Hishigi",
    "j": "足挫",
    "h": "נעילת אכילס",
    "m": "Achilles lock",
    "b": "Ashi (leg) + hishigi (crush / lever)",
    "c": "Leg locks"
  },
  {
    "r": "Ryo-Ashi-Hishigi",
    "j": "両足挫",
    "h": "נעילת שתי רגליים",
    "m": "Both-legs lock",
    "b": "Ryo (both) + ashi (leg) + hishigi (crush)",
    "c": "Leg locks"
  },
  {
    "r": "Ashi-Dori-Garami",
    "j": "足取緘",
    "h": "נעילת קרסול סובבת",
    "m": "Rolling ankle lock",
    "b": "Ashi (foot) + dori (catch) + garami (entanglement)",
    "c": "Leg locks"
  },
  {
    "r": "Hiza-Hishigi",
    "j": "膝挫",
    "h": "נעילת ברך",
    "m": "Knee lock",
    "b": "Hiza (knee) + hishigi (crush)",
    "c": "Leg locks"
  },
  {
    "r": "O-Soto-Gari",
    "j": "大外刈",
    "h": "קצירה חיצונית גדולה",
    "m": "Big outer reap",
    "b": "O (major) + soto (outer) + gari (reap)",
    "c": "Leg throws",
    "y": "c-A_nP7mKAc"
  },
  {
    "r": "O-Uchi-Gari",
    "j": "大内刈",
    "h": "קצירה פנימית גדולה",
    "m": "Big inner reap",
    "b": "O (major) + uchi (inner) + gari (reap)",
    "c": "Leg throws",
    "y": "0itJFhV9pDQ"
  },
  {
    "r": "Ko-Soto-Gari",
    "j": "小外刈",
    "h": "קצירה חיצונית קטנה",
    "m": "Small outer reap",
    "b": "Ko (minor) + soto (outer) + gari (reap)",
    "c": "Leg throws",
    "y": "jeQ541ScLB4"
  },
  {
    "r": "De-Ashi-Harai",
    "j": "出足払",
    "h": "סחיפת רגל קדמית",
    "m": "Forward foot sweep",
    "b": "De (advancing) + ashi (foot) + harai (sweep)",
    "c": "Leg throws",
    "y": "4BUUvqxi_Kk"
  },
  {
    "r": "Uchi-Mata",
    "j": "内股",
    "h": "קצירת ירך פנימית",
    "m": "Inner thigh throw",
    "b": "Uchi (inner) + mata (thigh)",
    "c": "Leg throws",
    "y": "iUpSu5J-bgw"
  },
  {
    "r": "Hiza-Guruma",
    "j": "膝車",
    "h": "גלגל ברך",
    "m": "Knee wheel",
    "b": "Hiza (knee) + guruma (wheel)",
    "c": "Leg throws",
    "y": "JPJx9-oAVns"
  },
  {
    "r": "Ashi-Barai",
    "j": "足払",
    "h": "סחיפת רגל",
    "m": "Foot sweep",
    "b": "Ashi (foot) + barai (sweep)",
    "c": "Leg throws"
  },
  {
    "r": "O-Goshi",
    "j": "大腰",
    "h": "זריקת מותן גדולה",
    "m": "Full hip throw",
    "b": "O (major) + goshi (hip throw)",
    "c": "Hip throws",
    "y": "yhu1mfy2vJ4"
  },
  {
    "r": "Harai-Goshi",
    "j": "払腰",
    "h": "זריקה בסחיפת מותן",
    "m": "Sweeping hip throw",
    "b": "Harai (sweep) + goshi (hip throw)",
    "c": "Hip throws",
    "y": "qTo8HlAAkOo"
  },
  {
    "r": "Hane-Goshi",
    "j": "跳腰",
    "h": "זריקה בקפיצת מותן",
    "m": "Spring hip throw",
    "b": "Hane (spring) + goshi (hip throw)",
    "c": "Hip throws",
    "y": "M9_7De6A1kk"
  },
  {
    "r": "Tsuri-Goshi",
    "j": "釣腰",
    "h": "זריקה בהרמת מותן",
    "m": "Lifting hip throw",
    "b": "Tsuri (lifting) + goshi (hip throw)",
    "c": "Hip throws",
    "y": "51Htlp7xEvE"
  },
  {
    "r": "Ushiro-Goshi",
    "j": "後腰",
    "h": "זריקת מותן נגדית",
    "m": "Rear hip throw",
    "b": "Ushiro (rear) + goshi (hip throw)",
    "c": "Hip throws",
    "y": "ORIYstuxYT8"
  },
  {
    "r": "Tomoe-Nage",
    "j": "巴投",
    "h": "זריקת מעגל",
    "m": "Circle throw",
    "b": "Tomoe (circle) + nage (throw)",
    "c": "Sacrifice throws",
    "y": "880WbHvHv6A"
  },
  {
    "r": "Ura-Nage",
    "j": "裏投",
    "h": "זריקה אחורית",
    "m": "Rear throw",
    "b": "Ura (rear) + nage (throw)",
    "c": "Sacrifice throws",
    "y": "Fgi9b8DJ5sQ"
  },
  {
    "r": "Tani-Otoshi",
    "j": "谷落",
    "h": "הפלת עמק",
    "m": "Valley drop",
    "b": "Tani (valley) + otoshi (drop)",
    "c": "Sacrifice throws",
    "y": "3b9Me3Fohpk"
  },
  {
    "r": "Yoko-Otoshi",
    "j": "横落",
    "h": "הפלה צידית",
    "m": "Side drop",
    "b": "Yoko (side) + otoshi (drop)",
    "c": "Sacrifice throws",
    "y": "MnNG67pF_a0"
  },
  {
    "r": "Tai-Otoshi",
    "j": "体落",
    "h": "הפלת גוף",
    "m": "Body drop",
    "b": "Tai (body) + otoshi (drop)",
    "c": "Hand throws",
    "y": "4x6S3Q-Ktv8"
  },
  {
    "r": "Ko-Uchi-Gari",
    "j": "小内刈",
    "h": "קצירה פנימית קטנה",
    "m": "Small inner reap",
    "b": "Ko (small) + uchi (inner) + gari (reap)",
    "c": "Leg throws",
    "y": "3Jb3tZvr9Ng"
  },
  {
    "r": "Ko-Soto-Gake",
    "j": "小外掛",
    "h": "קרס חיצוני קטן",
    "m": "Small outer hook",
    "b": "Ko (small) + soto (outer) + gake (hook)",
    "c": "Leg throws",
    "y": "8b6kY4s4zH4"
  },
  {
    "r": "Uki-Otoshi",
    "j": "浮落",
    "h": "הפלה צפה",
    "m": "Floating drop",
    "b": "Uki (floating) + otoshi (drop)",
    "c": "Hand throws",
    "y": "6H5tmncOY4Q"
  },
  {
    "r": "Sumi-Otoshi",
    "j": "隅落",
    "h": "הפלת פינה",
    "m": "Corner drop",
    "b": "Sumi (corner) + otoshi (drop)",
    "c": "Hand throws",
    "y": "lLU9wv52ni0"
  },
  {
    "r": "Sukui-Nage",
    "j": "掬投",
    "h": "זריקת חפינה",
    "m": "Scooping throw",
    "b": "Sukui (scoop) + nage (throw)",
    "c": "Hand throws",
    "y": "vU6aJ2kFxoI"
  },
  {
    "r": "Seoi-Nage",
    "j": "背負投",
    "h": "זריקת כתף",
    "m": "Shoulder throw",
    "b": "Seoi (carry on back) + nage (throw)",
    "c": "Shoulder throws",
    "y": "zIq0xI0ogxk"
  },
  {
    "r": "Ippon-Seoi-Nage",
    "j": "一本背負投",
    "h": "זריקת כתף ביד אחת",
    "m": "One-arm shoulder throw",
    "b": "Ippon (one) + seoi (back carry) + nage (throw)",
    "c": "Shoulder throws",
    "y": "FQnOlCxo4oI"
  },
  {
    "r": "Seoi-Otoshi",
    "j": "背負落",
    "h": "הפלת כתף",
    "m": "Shoulder drop",
    "b": "Seoi (back carry) + otoshi (drop)",
    "c": "Shoulder throws",
    "y": "vu1TMVNnq34"
  },
  {
    "r": "Kata-Guruma",
    "j": "肩車",
    "h": "גלגל כתף",
    "m": "Shoulder wheel",
    "b": "Kata (shoulder) + guruma (wheel)",
    "c": "Shoulder throws",
    "y": "cnHRhSy8yi4"
  },
  {
    "r": "Kubi-Hishigi",
    "j": "首挫",
    "h": "שבירת צוואר",
    "m": "Neck dislocation",
    "b": "Kubi (neck) + hishigi (crush / dislocate)",
    "c": "Neck locks"
  },
  {
    "r": "Osae-Hishigi",
    "j": "抑挫",
    "h": "שבירת צוואר בקיבוע",
    "m": "Neck dislocation in hold-down",
    "b": "Osae (hold-down) + hishigi (crush / dislocate)",
    "c": "Neck locks"
  },
  {
    "r": "Tate-Hishigi",
    "j": "縦挫",
    "h": "שבירת צוואר אנכית",
    "m": "Standing neck dislocation",
    "b": "Tate (vertical / standing) + hishigi (crush / dislocate)",
    "c": "Neck locks"
  },
  {
    "r": "Gyaku-Hishigi",
    "j": "逆挫",
    "h": "שבירת צוואר הפוכה",
    "m": "Reverse neck dislocation",
    "b": "Gyaku (reverse) + hishigi (crush / dislocate)",
    "c": "Neck locks"
  }
],
  roots: [
  {
    "r": "Nage",
    "k": "投",
    "en": "throw",
    "he": "זריקה",
    "group": "action"
  },
  {
    "r": "Goshi / Koshi",
    "k": "腰",
    "en": "hip throw",
    "he": "זריקת מותן",
    "group": "action"
  },
  {
    "r": "Gari",
    "k": "刈",
    "en": "reap",
    "he": "קצירה",
    "group": "action"
  },
  {
    "r": "Harai / Barai",
    "k": "—",
    "en": "sweep",
    "he": "סחיפה",
    "group": "action"
  },
  {
    "r": "Otoshi",
    "k": "—",
    "en": "drop",
    "he": "הפלה",
    "group": "action"
  },
  {
    "r": "Guruma",
    "k": "車",
    "en": "wheel",
    "he": "גלגל",
    "group": "action"
  },
  {
    "r": "Gatame",
    "k": "固",
    "en": "hold / lock",
    "he": "ריתוק / נעילה",
    "group": "action"
  },
  {
    "r": "Jime / Shime",
    "k": "絞",
    "en": "choke",
    "he": "חניקה",
    "group": "action"
  },
  {
    "r": "Garami",
    "k": "—",
    "en": "entanglement",
    "he": "כריכה",
    "group": "action"
  },
  {
    "r": "Hishigi",
    "k": "—",
    "en": "crush / lever",
    "he": "מנוף / שבירה",
    "group": "action"
  },
  {
    "r": "Te",
    "k": "手",
    "en": "hand",
    "he": "יד",
    "group": "body"
  },
  {
    "r": "Ude",
    "k": "腕",
    "en": "arm",
    "he": "זרוע",
    "group": "body"
  },
  {
    "r": "Hiza",
    "k": "膝",
    "en": "knee",
    "he": "ברך",
    "group": "body"
  },
  {
    "r": "Ashi",
    "k": "足",
    "en": "leg / foot",
    "he": "רגל",
    "group": "body"
  },
  {
    "r": "Kata",
    "k": "肩",
    "en": "shoulder",
    "he": "כתף",
    "group": "body"
  },
  {
    "r": "Koshi",
    "k": "腰",
    "en": "hip / waist",
    "he": "מותן",
    "group": "body"
  },
  {
    "r": "Kubi",
    "k": "首",
    "en": "neck",
    "he": "צוואר",
    "group": "body"
  },
  {
    "r": "Mata",
    "k": "股",
    "en": "thigh",
    "he": "ירך",
    "group": "body"
  },
  {
    "r": "Ha",
    "k": "羽",
    "en": "wing",
    "he": "כנף",
    "group": "body"
  },
  {
    "r": "Eri",
    "k": "—",
    "en": "collar / lapel",
    "he": "דש",
    "group": "body"
  },
  {
    "r": "O",
    "k": "大",
    "en": "major / big",
    "he": "גדול",
    "group": "mod"
  },
  {
    "r": "Ko",
    "k": "小",
    "en": "minor / small",
    "he": "קטן",
    "group": "mod"
  },
  {
    "r": "Kata",
    "k": "片",
    "en": "single / one side",
    "he": "אחד / צד אחד",
    "group": "mod"
  },
  {
    "r": "Uchi",
    "k": "内",
    "en": "inner",
    "he": "פנימי",
    "group": "mod"
  },
  {
    "r": "Soto",
    "k": "外",
    "en": "outer",
    "he": "חיצוני",
    "group": "mod"
  },
  {
    "r": "Mae",
    "k": "—",
    "en": "front",
    "he": "קדמי",
    "group": "mod"
  },
  {
    "r": "Ushiro",
    "k": "—",
    "en": "rear",
    "he": "אחורי",
    "group": "mod"
  },
  {
    "r": "Yoko",
    "k": "横",
    "en": "side",
    "he": "צד",
    "group": "mod"
  },
  {
    "r": "De",
    "k": "出",
    "en": "advancing",
    "he": "מתקדם",
    "group": "mod"
  },
  {
    "r": "Ryo / Morote",
    "k": "両",
    "en": "both / two hands",
    "he": "שתי ידיים",
    "group": "mod"
  },
  {
    "r": "Juji",
    "k": "十字",
    "en": "cross (+)",
    "he": "צלב",
    "group": "mod"
  },
  {
    "r": "Gyaku",
    "k": "逆",
    "en": "reverse",
    "he": "הפוך",
    "group": "mod"
  },
  {
    "r": "Nami",
    "k": "並",
    "en": "normal",
    "he": "רגיל",
    "group": "mod"
  },
  {
    "r": "Kami",
    "k": "上",
    "en": "upper",
    "he": "עליון",
    "group": "mod"
  },
  {
    "r": "Sankaku",
    "k": "—",
    "en": "triangle",
    "he": "משולש",
    "group": "mod"
  },
  {
    "r": "Kuzure",
    "k": "崩",
    "en": "broken",
    "he": "שבור",
    "group": "special"
  },
  {
    "r": "Shiho",
    "k": "四方",
    "en": "four directions",
    "he": "ארבעה כיוונים",
    "group": "special"
  },
  {
    "r": "Hammerlock",
    "k": "—",
    "en": "English term",
    "he": "נעילת יד מאחורי הגב",
    "group": "special"
  }
]
};
